services:
  - type: web
    name: agentzero-ui
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn agentzero_ui:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.2
    plan: free